#! /bin/bash
#
#  Start Stop and Monitor for grades server
#

PROG="runOnAWS"

function start {
    echo "Starting Meteor via Passenger instance: "
    cd /home/ubuntu/grades-toolkit/app
    sudo ./$PROG
}

function stop {
    sudo passenger stop --pid-file /home/ubuntu/grades-toolkit/app/tmp/pids/passenger.80.pid
}



function status {
    sudo passenger status --pid-file /home/ubuntu/grades-toolkit/app/tmp/pids/passenger.80.pid
}

function logs {
    tail -f /home/ubuntu/grades-toolkit/app/log/passenger.80.log
}

case $1 in
    start)
        start;
        ;;
    stop)
        stop;
        ;;
    restart)
        stop;
        start;
        ;;
    status)
        status;
        ;;
    logs)
        logs;
        ;;
    *)
        echo "Valid commands: "
        echo "start | stop | restart | status | logs"
        ;;
esac;