#!/bin/bash

# 
# StartUp Script for the AWS Site using passenger
#

# Meteor Environment Variables
export MONGO_URL='mongodb://localhost:27017/grades'
export ROOT_URL='https://grades.sharedrecords.org/'


# Start Passenger Standalone in daemonized mode. Passenger will be started as
# root when run from this file, so we also tell it to drop its privileges to a
# normal user. Replace 'someusername' with the user you want to run your
# application under.  Using ec2-user for now probably should switch to something else

passenger start --user ubuntu --daemonize 

echo " To stop passenger run:"                                                                                                                                                                 
echo "    sudo passenger stop"
echo "  or "
echo "    sudo passenger stop --pid-file /home/ubuntu/grades-toolkit/app/tmp/pids/passenger.80.pid"


