#!/bin/bash

# 
# StartUp Script for the AWS Site using Passenger
#

# Export Path for Passenger                                                                                                                                          
export PATH=/opt/passenger/passenger/bin:$PATH

# Meteor Environment Variables
export MONGO_URL='mongodb://localhost:27017/grades'
export ROOT_URL='http://grades.sharedrecords.org/'


# Start Passenger Standalone in daemonized mode. Passenger will be started as
# root when run from this file, so we also tell it to drop its privileges to a
# normal user. Replace 'someusername' with the user you want to run your
# application under.  Using ec2-user for now probably should switch to something else
passenger start --port 80 --user ubuntu --environment production --daemonize 

#To stop Passenger Standalone, run:                                                                                                                                  
#                                                                                                                                                                    
#   sudo passenger stop --pid-file /home/bia/src/bia-website/app/tmp/pids/passenger.80.pid                                                                                                                                             

# Old way
#meteor run --port 80 